### PR TITLE
Added configurable way to check capabilities but only log the result

### PR DESCRIPTION
**Pull request by kristinaspring**
fixes https://github.com/xmidt-org/tr1d1um/issues/136
once [this pr](https://github.com/xmidt-org/webpa-common/pull/449) in webpa-common is merged and a new version is released, this pr can be updated and merged.

### CODE REVIEW

**Comment by johnabass** [comment]
This, like the scytale PR, looks great.  I'll have Joel take a look, though.

**Comment by joe94** [comment]
Looks good otherwise! 🍾

**Comment by kristinaspring** [comment]
@joe94, The functions in these changes do belong in webpa-common, there is already an issue: https://github.com/xmidt-org/webpa-common/issues/422

I have looked at consolidating the functions before, but with differences between scytale, tr1d1um, gungnir, and now talaria, it is getting more and more difficult to consolidate them.   Not sure when the consolidation will get done, but it's not in scope for these changes.

**Comment by joe94** [comment]
Gotcha, hopefully we'll have better ideas the more established our code across the services look.

**Comment by kristinaspring** [comment]
also fixes https://github.com/xmidt-org/tr1d1um/issues/124

**Pull request merged**
